### ISSUE TITLE
Build Fails as ClassAndTypeBasedSchemaBlockerTest Fails 

### ISSUE THREAD

**Issue by aijdissanayake** [olehmberg/T2KMatch#2]
I tried to build the project and the build fails as the following assertion
```
//check for size
 assertEquals(4, blockedPairs.size());
```
in `ClassAndTypeBasedSchemaBlockerTest.java` test file fails.

**Error:**

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.19 sec <<< FAILURE! - in de.uni_mannheim.informatik.dws.t2k.match.blocking.ClassAndTypeBasedSchemaBlockerTest
testRunBlocking(de.uni_mannheim.informatik.dws.t2k.match.blocking.ClassAndTypeBasedSchemaBlockerTest)  Time elapsed: 0.189 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<4> but was:<0>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:201)
	at junit.framework.Assert.assertEquals(Assert.java:207)
	at de.uni_mannheim.informatik.dws.t2k.match.blocking.ClassAndTypeBasedSchemaBlockerTest.testRunBlocking(ClassAndTypeBasedSchemaBlockerTest.java:75)
```

**Comment by olehmberg** [comment]
Hi and thanks for the feedback. I just compiled the code and ran the tests without problems. Are you running the tests with maven? If not, please try. It could be that your working directory is not set correctly an the test didn't load the data files.
